### ISSUE TITLE
Searches return no results, what am I doing wrong?

### ISSUE THREAD

**Issue by elijah** [raks81/rally-cli#3]
Hi there.  I'm trying to make this tool work with rally - I feel like there's a missing piece here that could/should be better documented.

I've got an API key - that works - I've validated that by switching to password authentication (by removing my API key from the config and switching to user/pass environment variables for the underlying rally node module, and then making the password 'wrong'...)

When I search I get no results for any of the iterations that I've specified.  Because I thought it might be symptomatic of a weird config in someone's very complex rally config - I went and made an evaluation account to figure out tooling with.   So now I'm working with just the sample issues that get populated into a new account - "Iteration 1 - Browse and Book" etc - the safari-trip-themed demo cards.

A little confused by the instructions in the config file - where it tells you where to pick up the project ID.  The integers-only portion of that turns out to be the proper project ID, right?  [In the default case of the 'default workspace, default project' you get for a simple rally config, at least...]

I'd be happy to help debug this interactively with you - over screenhero or whatever - if the code is still working for you.  ;-)

Config currently looks like this:

``` 
{
  "apiKey": "xxxxxxxxxxxxxx",
  "projects": [
    {
      "name": "Iteration 1 - Browse and Book",
      "id": "/project/87297589084",
      "currentItr": "Iteration 1 - Browse and Book"
    },
    {
      "name": "Iteration 2",
      "id": "/project/87297589084",
      "currentItr": "Iteration 2 - Streamline Operations"
    },
    {
      "name": "Unscheduled",
      "id": "/project/87297589084",
      "currentItr": "Unscheduled"
    }
  ],
  "user": "elw@stderr.org",
  "uiLaunchCommand": "open -a Firefox https://rally1.rallydev.com/#/87297589084d",
  "rallySearchCommand": "open -a Firefox https://rally1.rallydev.com/#/87297589084d/search?keywords=${keyword}",
  "holidays": [
    "08 Apr 2016",
    "14 Apr 2016"
  ]
}
```

**Comment by rr-on-gh** [comment]
@elijah So I have moved out of the team that uses Rally and my new team does not use Rally, so I am not really maintaining this anymore, but happy to help :)
I tried the cli just now and since I still have access to Rally I am able to see my old iteration tasks fine. So looks like an issue with your configuration. In my case, the project id is numeric part in this URL:
https://rally1.rallydev.com/#/47349908541ud/teamstatus
We can debug this together if you still interested.
